Le_Domain='econet.dpdns.org'
Le_Alt='no'
Le_Webroot='no'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme.zerossl.com/v2/DV90'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme.zerossl.com/v2/DV90/order/BcNsBoxKAYrgvfXf1MOsdA/finalize'
Le_LinkOrder='https://acme.zerossl.com/v2/DV90/order/BcNsBoxKAYrgvfXf1MOsdA'
Le_LinkCert='https://acme.zerossl.com/v2/DV90/cert/MIRyVxFywcOz91Ke7Djw0A'
Le_CertCreateTime='1780475937'
Le_CertCreateTimeStr='2026-06-03T08:38:57Z'
Le_NextRenewTimeStr='2026-08-19T08:38:56Z'
Le_NextRenewTime='1787128736'
