

#LOG_FILE="/root/.acme.sh/acme.sh.log"
#LOG_LEVEL=1

#AUTO_UPGRADE="1"

#NO_TIMESTAMP=1

    
ACCOUNT_EMAIL='tafnyoni123@gmail.com'
UPGRADE_HASH='f265c304daf53afdf26c3e6346f393d9d098c804'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
