CA_EMAIL='tafnyoni123@gmail.com'
CA_EAB_KEY_ID='SMJQ0ku1TkCUPLZ2TQPSzQ'
CA_EAB_HMAC_KEY='ZRz7YIhT55k924TXJCzNAcQ5JAKYu1ixd49T964dLDJOIIxF_RvM6vNXWKSOjmQFp-vVq88KsB2mZdfYU0FR8g'
ACCOUNT_URL='https://acme.zerossl.com/v2/DV90/account/SMJQ0ku1TkCUPLZ2TQPSzQ'
CA_KEY_HASH='DqE7sK2wnYyJqQGkF3BQ4v5/FfqrG6pMwqkxYF/YCY8='
